In [11]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd

In [2]:
df = pd.read_csv("/home/mark/egyetem/4.felev/Gépi tanulás/practice/MultivariantRegression/Exercise/hiring.csv")
df

experience  test_score  interview_score  salary
0         NaN         8.0                9   50000
1         NaN         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [5]:
# filling NaN experience fields with 0 as a replacement value
df.experience = df.experience.fillna(0)
df

experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [9]:
# calculating median value
import math
median_score = math.floor(df.test_score.median())
# replacing NaN values with this median
df.test_score = df.test_score.fillna(median_score)
df

experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [13]:
reg = LinearRegression()
reg.fit(df[['experience', 'test_score', 'interview_score']], df.salary)

LinearRegression()

In [14]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [15]:
reg.intercept_

17737.26346433768

In [16]:
reg.predict([[2, 9, 6]])

array([53205.96797671])

In [17]:
reg.predict([[12, 10, 10]])

array([92002.18340611])