In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
data_frame = pd.read_csv("/home/mark/egyetem/4.felev/Gépi tanulás/practice/MultivariantRegression/homeprices.csv")
data_frame

area  bedrooms  age  price
0  2600       3.0   20  55000
1  3000       4.0   15  56500
2  3200       NaN   18  61000
3  3600       3.0   30  59500
4  4000       5.0    8  76000

In [7]:
import math
# dealing with NaN values by replacing them by the median of the column
median_bedrooms = math.floor(data_frame.bedrooms.median())
median_bedrooms

3

In [12]:
# filling the NaN columns
data_frame.bedrooms = data_frame.bedrooms.fillna(median_bedrooms)
data_frame

area  bedrooms  age  price
0  2600       3.0   20  55000
1  3000       4.0   15  56500
2  3200       3.0   18  61000
3  3600       3.0   30  59500
4  4000       5.0    8  76000

In [14]:
reg = linear_model.LinearRegression()
# in the first parameter we list de independent variables (area, bedrooms, age)
# and in the second parameter we write the target variable, the dependent one

# y = m1*x1 + m2.x2 + m3 + b
# where m1, m2, m3 are the coeficients, y is the target, and b is the intercept
reg.fit(data_frame[['area', 'bedrooms', 'age']], data_frame.price)

LinearRegression()

In [18]:
reg.coef_

array([   13.725, -2602.5  ,  -682.5  ])

In [19]:
reg.intercept_

38372.49999999998

In [21]:
reg.predict([[3000, 3, 15]])

array([61502.5])

In [22]:
13.725*3000-2602.5*3-682.5*15+38372.5

61502.5

In [23]:
reg.predict([[2500, 4, 5]])

array([58862.5])